# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 引入配置文件

target 'NEGameSample' do
  pod 'IHProgressHUD'
  pod 'LottieSwift', :path=> '../../../third_party/lottie/LottieSwift.podspec'
  pod 'Masonry','1.1.0'
  pod 'NECommonKit','9.6.3'
  pod 'NECommonUIKit', '9.6.4-alpha01'
  pod 'NECoreIMKit','9.6.3'
  pod 'NECoreKit','9.6.4'
  pod 'NEGameKit', :path=> '../NEGameKit/NEGameKit.podspec'
  pod 'NEGameUIKit', :path=> '../NEGameUIKit/NEGameUIKit.podspec'
  pod 'NELoginSample', :path=> '../../../OneOnOne/NELoginSample/NELoginSample.podspec'
  pod 'NERoomKit/Special_All','1.22.0'
  pod 'NERtcSDK_Special/RtcBasic','5.5.203'
  pod 'NESocialUIKit', :path=> '../../../Party/NESocialUIKit/NESocialUIKit.podspec'
  pod 'NEUIKit', :path=> '../../../UIKit/NEUIKit/NEUIKit.podspec'
  pod 'NEVoiceRoomBaseUIKit', :path=> '../../NEVoiceRoomBaseUIKit/NEVoiceRoomBaseUIKit.podspec'
  pod 'NEVoiceRoomKit', :path=> '../../NEVoiceRoomKit/NEVoiceRoomKit.podspec'
  pod 'NIMSDK_LITE','9.12.0'
  pod 'SDWebImage','5.15.4'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

# 工程的podspec引用采用源码的环境变量
ENV['USE_SOURCE_FILES'] = 'true'



#源码依赖


#登录



#远端依赖
#GitPushStart
#GitPushEnd




end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end

